// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package gqlmodels

type PostInput struct {
	Title   *string `json:"title"`
	Content *string `json:"content"`
	UserID  *string `json:"userId"`
}

type UserInput struct {
	Email       *string `json:"email"`
	UserID      *string `json:"userId"`
	DisplayName *string `json:"displayName"`
	Name        *string `json:"name"`
	FirstName   *string `json:"firstName"`
	LastName    *string `json:"lastName"`
	NickName    *string `json:"nickName"`
	Description *string `json:"description"`
	Location    *string `json:"location"`
}
